<script setup>
const besovImage = new URL('@/assets/img/Besov.jpg', import.meta.url).href
</script>

<template>
  <div id="tooplate_main">
    <div id="about" class="main_box">
      <h1>About</h1>

      <img src="@/assets/img/94-vagif-guliyev.jpg" alt="image" class="img_float_r img_frame" />

      <ul>
        <li>Date of birth: 22 Feb 1957</li>
        <li>Place of Birth: Salyan, Azerbaijan</li>
        <!-- <li>Married, 3 sons, 7 grandchildren</li> -->
        <li>Member of New Azerbaijan Party</li>
        <li>Corresponding-member of Azerbaijan National Academy of Sciences</li>
        <li>Deputy Director of Institute of Mathematics and Mechanics, Azerbaijan</li>
        <li>Visitor Professor of DUMLIPINAR University, Kutahya, Turkey</li>
        <li>Professor of Baku State University, Baku, Azerbaijan Republic</li>
        <li>Professor of RUDN University, Moscow, Russian Federation</li>
        <li>Visitor Professor of Ahi Evran University 2009-2018, Kirsehir, Turkey</li>
        <li>Supervised 20 PhD and 4 Post Doctorate students</li>
        <li>Published of more than 200 publications worldwide</li>
        <li>Participated in more than 30 International conferences</li>
        <li>2 published books and 2 upcoming books</li>
        <li>More than 50 Academic visits</li>
        <li>12 International award-winning grants/prizes</li>
        <li>About 10 Awards/Honours</li>
        1w
        <li>Editor-in-chief of 2 journals</li>
        <li>Editor of 8 International journals</li>
        <li>Referee for 44 International Scientific journals</li>
        <li>47 publications in Conferences</li>
        <li>169 publications in International Refereed Journal Publications</li>
        <li>45 publications in Azerbaijan Science Journals</li>
      </ul>

      <div class="cleaner h40"></div>
      <div class="col_12 float_l">
        <h3><em>Area of Interest</em></h3>
        <blockquote>
          <p>• Potential type operators on Lie groups or homogeneous spaces</p>
          <cite>• Singular integral operators on Lie groups or homogeneous spaces<span> </span></cite>
        </blockquote>

        <blockquote>
          <p>• Function spaces on Lie groups or homogeneous spaces</p>
          <cite>• Banach-valued Function spaces of fractional smoothness<span> </span></cite>
        </blockquote>

        <blockquote>
          <p>• Integral operators on strictly pseudo-convex domains in Cn</p>
          <cite>• Function spaces on strictly pseudo-convex domains in Cn<span> </span></cite>
        </blockquote>

        <blockquote>
          <p>• Solvability and other properties of invariant partial differential equations on Lie groups</p>
          <cite>• Singular integrals, maximal functions and other integral operators, generated by Bessel diferential operators <span> </span></cite>
        </blockquote>

        <blockquote>
          <p>• Bessel harmonic analysis and applications</p>
          <cite> <span> </span></cite>
        </blockquote>
      </div>
      <div class="col_12 float_r">
        <h3><em>Official Recommendations</em></h3>
        <ul class="tooplate_list">
          <li>
            <img :src="besovImage" alt="image" class="img_float_r img_frame" />
            <a href="http://www.mi-ras.ru/~besov/" target="_blank" rel="nofollow">
              <em><strong>Besov Oleg Vladimirovich</strong> </em>
            </a>
            Professor,
            <br />
            Doctor of Sciences, <br />Correspondence Member of Russian Academy of Sciences
            <a href="/pdf/vagifguliyev_ref1_ru.pdf" target="_blank" title="Reference from O.V.Besov in Russian">
              <img src="@/assets/img/pdf_ru.png" height="60px" width="60px" />
            </a>
          </li>

          <li>
            <img src="@/assets/img/Victor_Burenkov.jpg" alt="image" class="img_float_r img_frame" />
            <a href="http://www.enu.kz/ru/lica-enu/burenkov-viktor-ivanovich/" target="_blank" rel="nofollow">
              <em><strong>Burenkov Victor Ivanovich</strong> </em>
            </a>
            <br />Professor, <br />
            Doctor of Sciences, <br />
            Professor of Cardiff University, <br />
            Vice-President of
            <a href="http://isaacmath.org/home/" target="_blank"> <em title="The International Society for Analysis, its Applications and Computation">ISAAC</em> </a><br />
            <a href="/pdf/vagifguliyev_ref2_ru.pdf" target="_blank" title="Reference from V.I.Burenkov in RUSSIAN">
              <img src="@/assets/img/pdf_ru.png" height="60px" width="60px" />
            </a>
            <a href="/pdf/vagifguliyev_ref1_ru.pdf" target="_blank">Open PDF</a>
          </li>

          <li>
            <img src="@/assets/img/reshyug.jpg" alt="image" class="img_float_r img_frame" />
            <a href="http://www.math.nsc.ru/LBRT/u2/nauka/reshetny.html" target="_blank" rel="nofollow">
              <em><strong>Reshetnyak Yurii Grigorievich </strong></em>
            </a>
            <br />Professor, <br />Full member of Russian Academy of Sciences <br />
            <a href="/pdf/vagifguliyev_ref1_ru.pdf" target="_blank" title="Reference from O.V.Besov in Russian">
              <img src="@/assets/img/pdf_ru.png" height="60px" width="60px" />
            </a>
          </li>

          <li>
            <a href="http://w3.ualg.pt/~ssamko/" target="_blank" rel="nofollow">
              <em><strong>Samko Stefan Grigorievich</strong></em>
            </a>
            <img src="@/assets/img/samko.jpg" alt="image" class="img_float_r img_frame" />
            <br />Professor of <br />
            University of Algarve Portugal, <br />Professor of <br />Federal Southern University <br />
            Russia <br />
            <a href="/pdf/vagifguliyev_ref4_ru.pdf" target="_blank" title="Reference from S.G.SAMKO in RUSSIAN">
              <img src="@/assets/img/pdf_ru.png" height="60px" width="60px" />
            </a>
            <a href="/pdf/vagifguliyev_ref4_en.pdf" target="_blank" title="Reference from S.G.SAMKO in ENGLISH">
              <img src="@/assets/img/pdf_en.png" height="60px" width="60px" />
            </a>
          </li>
        </ul>
      </div>
      <div class="cleaner"></div>
      <a href="#tooplate_main" class="gototop">Go To Top</a>
      <div class="cleaner"></div>
    </div>
    <!-- END of about -->
  </div>
</template>
