<template>
  <div id="tooplate_main">
    <div id="about" class="main_box">
      <h1>PhD and Doctorate Students</h1>
      <h3><em>20 Ph.D. students</em></h3>

      <p>
        1. <font color="white">K.R. Rahimova</font> <br />Investigations of the boundedness of some class anisotropic operators in the Morrey type spaces. <br />
        AZERBAIJAN, 2016, November 25
      </p>
      <p>
        2. <font color="white">Isayev, F.A.</font>, Investigations two-weighted inequalities for Fourier-Bessel integral operators.<br />
        AZERBAIJAN, 2015, November 27
      </p>
      <p>3. <font color="white">Serab Guner</font>, The singular integral operators related to generalized shift operator in Beppo-Levi spaces. <br />TURKEY, Dumlupinar University,2015, June 11</p>
      <p>
        4. <font color="white">Cansu Keskin</font><br />The singular integral operators related to generalized shift operator in Beppo-Levi spaces. <br />
        TURKEY, Dumlupinar University,2015, June 11
      </p>
      <p>
        5. <font color="white">Fatih Deringoz</font> <br />Boundedness of integral operators of harmonic analysis on generalized Orlicz-Morrey spaces. <br />
        TURKEY, Ahi Evran University, 2015, June 09
      </p>
      <p>
        6. <font color="white">Altinkol Seyda</font><br />
        Some problems of B-harmonic analysis. <br />TURKEY, Akdeniz University, 2014, December 29
      </p>
      <p>
        7. <font color="white">Muradova Sh.A.</font> Study anisotropic fractional maximal operator and Riesz potential on anisotropic local Morrey type spaces. <br />AZERBAIJAN, 2013, September 27
      </p>
      <p>8. <font color="white">Canay Aykol</font><br />Generalized Morrey-Lorentz spaces and the boundedness of the maximal operators in this spaces. <br />TURKEY, Ankara Universty, 2013</p>
      <p>
        9. <font color="white">Aliyev, S.S.</font><br />
        Aprior estimates of the elliptic differential equations on the generalized Morrey spaces.<br />
        Institute of Mathematics and Mechanics of Academy of Sciences of Azerbaijan, 2012, November 25
      </p>
      <p>
        10. <font color="white">Karaman Turhan</font><br />
        Boundedness of the sublinear operators, generated by Calderon-Zygmund operators on generalized weighted Morrey spaces.<br />TURKEY, Ankara Universty, 2012, May 25
      </p>
      <p>11. <font color="white">Omarova M.N.</font><br />On the properties of the fractional maximal functions and the Riesz potentials on the Laguerre hypergroups.<br />AZERBAIJAN, 2010, May 14</p>
      <p>12. <font color="white">Hajiyev A.I.</font><br />Weighted inequalities for integral operators, associated by Bessel differential operators.<br />AZERBAIJAN, 2006, June 23</p>
      <p>13. <font color="white">Garakhanova N.N.</font><br />Investigations of the B<sub>k,n</sub> maximal functions and B<sub>k,n</sub> Riesz potentials.<br />AZERBAIJAN, 2005, October 17</p>
      <p>
        14. <font color="white">Abbasova M.M.</font><br />Structural property singular integrals for banach-valued functions.<br />
        AZERBAIJAN, 2005, February 7
      </p>
      <p>
        15. <font color="white">Safarov Z.V.</font><br />Some properties of generalized Fourier-Bessel potential type integrals.<br />
        AZERBAIJAN, 2004, April 05
      </p>
      <p>16. <font color="white">Bandaliyev R.A.</font><br />Imbedding theorems for weighted Sobolev spaces Banach valued functions.<br />AZERBAIJAN, 2002, November 26</p>
      <p>17. <font color="white">Narimanov A.K.</font><br />Investigations of the anisotropic Fourier–Bessel singular integrals.<br />AZERBAIJAN, 2001, February 7</p>
      <p>18. <font color="white">Maharov I.K.</font><br />The equivalents norms in the Banach-valued Besov spaces. <br />AZERBAIJAN, 2000, May 17</p>
      <p>
        19. <font color="white">Gasanov D.D.</font><br />Anisotrop Bn–potential Riesz and its applications.<br />
        AZERBAIJAN, 1999, June 23
      </p>
      <p>
        20. <font color="white">Mustafaev R.Ch.</font><br />Integral operators of potential type on spaces of homogeneous type and their applications to differential equations.<br />AZERBAIJAN, 1998,
        September 16
      </p>

      <h3><em>4 Doctorate students</em></h3>

      <p>1. <font color="white">Bandaliyev R.A.</font><br />Integral operators of harmonic analysis in Banach function spaces and some applications.<br />AZERBAIJAN, 2014, December 05</p>

      <p>2. <font color="white">Yagubov Y.Y.</font><br />Integral operators connected with Dunkel operator and determined in Heisenberg group in functional spaces.<br />AZERBAIJAN, 2015, May 22</p>

      <p>3. <font color="white">Ibrahimov E.C.</font><br />Some aspects of harmonic analysis associated with Gegenbauer differential operator.<br />AZERBAIJAN, 2017, September 29</p>

      <p>
        4. <font color="white">Hasanov J.J.</font><br />Integral operators of multidimensional harmonic analysis and B- harmonic analysis in generalized Morrey spaces and some applications. <br />
        AZERBAIJAN, 2018, February 02
      </p>

      <div class="cleaner"></div>
    </div>
    <!-- END of about -->
  </div>
</template>
